# Generated by Django 4.2.4 on 2023-08-28 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2023, 8, 28, 16, 10, 35, 329850)),
        ),
    ]
